spring:
  application:
    name: sender
  rabbitmq:
    host: <rabbitmq-host>
    port: <rabbitmq-port>
    username: <rabbitmq-username>
    password: <rabbitmq-password>
    virtual-host: <rabbitmq-virtual-host-name>
    queue:
      name: nmd_first_queue
      json-queue-name: nmd_json_queue
    exchange:
      name: nmd_first_exchange
    binding:
      routing-key: nmd_routing_key
      routing-json-queue-key: nmd_json_routing_key
  datasource:
    url: <postgre-host-url>
    username: <postgre-username>
    password: <postgre-password>
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # Maximum number of connections in the pool
      minimum-idle: 2 # Minimum number of idle connections to maintain
      idle-timeout: 30000 # Maximum idle time for connections (in milliseconds)
      max-lifetime: 1800000 # Maximum lifetime of a connection (in milliseconds)
      connection-timeout: 30000 # Maximum time to wait for a connection (in milliseconds)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9091
